services:
    db:
        image: postgres:17
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=payments_db
        ports:
            - "5432:5432"
