services:
    db:
        image: postgres:17
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=payments_db
        ports:
            - "5432:5432"
    backend-1:
        image: danielbatata/img-rinha-elixir:0.0.2
        depends_on:
            - db
        environment:
            - SECRET_KEY_BASE=bababui
            - DATABASE_URL=ecto://postgres:password@db/payments_db
            - PHX_SERVER=true
            - PHX_HOST=localhost
            - PORT=4000
        ports:
            - "4000:4000"
