services:
    db:
        image: postgres:17
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
            - POSTGRES_DB=payments_db
        ports:
            - "5432:5432"
    backend-1:
        image: danielbatata1/img-rinha-elixir:0.0.1
        depends_on:
            - db
        environment:
            - SECRET_KEY_BASE="bababui"
            - DATABASE_URL=ecto://postgres:password@db/payments_db
        ports:
            - "4000:4000"
